struct node {
    char name[256]; 
    char artist[256]; 
    struct node *next;
};
void to_lowercase(char str[]);
void print_list(struct node *head);
struct node* insert_front(struct node head[], char newname[], char newart[]);
int list_len(struct node *head);
struct node* free_list(struct node *head);
struct node* find_name(struct node *head, char* s);
struct node* find_artist(struct node *head, char* s);
struct node* random_pick(struct node *head);
struct node* insert_order(struct node head[], char newname[], char newart[]);
struct node* remove_node(struct node *head, struct node *to_remove);
struct node* remove_node(struct node *head, struct node *to_remove);
struct node* lib_add(struct node *arr[27],char *newname, char *newart);
struct node* lib_artist_pick(struct node *arr[27],char *artistname);
void print_artist_songs(struct node *arr[27], char *artistname);
void print_lib(struct node *arr[27]);
struct node* random_lib(struct node *arr[27]);
void print_shuffle(struct node * arr[27], int i);
void print_letter(struct node * arr[27], char c);
struct node *search_song(struct node * arr[27], char  *n, char *a);
void delete_song(struct node *arr[27], char *n, char *a);
void delete_all_songs(struct node *arr[27]);
